# Generated by Django 4.1 on 2022-09-07 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('system_info', models.CharField(blank=True, choices=[('MACOS', 'macOS'), ('WINDOWS', 'Windows')], max_length=20, verbose_name='Операционная система')),
                ('price', models.FloatField(max_length=20, verbose_name='Цена')),
                ('picture', models.ImageField(default='noimage.png', upload_to='laptops/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
