# Generated by Django 4.1 on 2022-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('system_info', models.CharField(choices=[('MACOS', 'macOS'), ('WINDOWS', 'Windows')], default='WINDOWS', max_length=20)),
                ('price', models.FloatField(max_length=20)),
                ('picture', models.ImageField(upload_to='laptops/')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
