# Generated by Django 4.1 on 2022-09-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='noimage.png', upload_to='laptops/'),
        ),
    ]
