# Generated by Django 4.1 on 2022-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='system_info',
            field=models.CharField(blank=True, choices=[('macOS', 'macOS'), ('Windows', 'Windows'), ('iOS', 'iOS'), ('Adnroid', 'Android')], max_length=20, verbose_name='Операционная система'),
        ),
    ]
