# Generated by Django 4.1 on 2022-09-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_goods_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(max_length=20, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='system_info',
            field=models.CharField(choices=[('MACOS', 'macOS'), ('WINDOWS', 'Windows')], default='WINDOWS', max_length=20, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
