# Generated by Django 4.1 on 2022-09-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='manufacturer',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
