# Generated by Django 4.1 on 2022-09-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_goods_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
