# Generated by Django 4.1 on 2022-09-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_goods_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='system_info',
            field=models.CharField(blank=True, choices=[('macOS', 'macOS'), ('Windows', 'Windows'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=20, verbose_name='Операционная система'),
        ),
    ]
